language: php
php:
  - '5.6'
  - '7.0'
  - nightly
sudo: required
services:
  - rabbitmq
before_install:
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
install:
  - composer global require -n fxp/composer-asset-plugin
  - composer install -n